import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from "../../public/images/profile/Aradhana1.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>
        <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout clssName='pt-0'>
          <div className="flex items-center justify-between w-full">

            <div className='w-1/2'>

              <Image src={profilePic} alt="ABHI" className="w-full h-auto" />
            </div>
            <div>
              <h1>Turning Vision Into Reality With Code And Design.</h1>
              <p>
              As a skilled UI UX Designer, I am dedicated to turning ideas into innovative web design applications. 
Explore my latest projects and articles, showcasing my expertise in Figma and Illustration.
              </p>
              </div>
          </div>
        </Layout>
        </main>
    </>
  );
}
